export const keyMap = {
  KeyQ: 'C3',
  Digit2: 'C#3',
  KeyW: 'D3',
  Digit3: 'D#3',
  KeyE: 'E3',
  KeyR: 'F3',
  Digit5: 'F#3',
  KeyT: 'G3',
  Digit6: 'G#3',
  KeyY: 'A3',
  Digit7: 'A#3',
  KeyU: 'B3',
  KeyZ: 'C4',
  KeyS: 'C#4',
  KeyX: 'D4',
  KeyD: 'D#4',
  KeyC: 'E4',
  KeyV: 'F4',
  KeyG: 'F#4',
  KeyB: 'G4',
  KeyH: 'G#4',
  KeyN: 'A4',
  KeyJ: 'A#4',
  KeyM: 'B4',
  Comma: 'C5'
};
